name: aggregate-deployments-action
description: Aggregate GitHub Deployments against commit SHA

inputs:
  sha:
    description: commit SHA or ref
    required: true
    default: ${{ github.event.pull_request.head.sha || github.sha }}
  token:
    description: GitHub token
    required: true
    default: ${{ github.token }}

outputs:
  progressing:
    description: true if any deployment is progressing
  completed:
    description: true if all deployments are completed
  succeeded:
    description: true if all deployments are succeeded
  summary:
    description: markdown list of all deployments

runs:
  using: 'node16'
  main: 'dist/index.js'
