name: typescript-action
description: Template of TypeScript Action

inputs:
  sha:
    description: commit SHA or ref
    required: true
    default: ${{ github.event.pull_request.head.sha || github.sha }}
  token:
    description: GitHub token
    required: true
    default: ${{ github.token }}

outputs:
  completed:
    description: true if all deployments are completed
  success:
    description: true if all deployments are success
  summary:
    description: markdown list of all deployments

runs:
  using: 'node16'
  main: 'dist/index.js'
