name: delete-outdated-deployments

on:
  schedule:
    - cron: '0 0 * * *'
  pull_request:
    paths:
      - .github/workflows/delete-outdated-deployments.yaml

jobs:
  delete:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: int128/delete-deployments-action@91ac44bd80a85d7d7dc7755ef1ad22f5cc75734a # v1.16.0
