name: delete-outdated-deployments

on:
  schedule:
    - cron: '0 0 * * *'
  pull_request:
    paths:
      - .github/workflows/delete-outdated-deployments.yaml

jobs:
  delete:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: int128/delete-deployments-action@f9e1df5b0fd419802b519cbfc6dcaa7c5c5791af # v1.13.0
