name: ts

on:
  pull_request:
    paths:
      - src/**
      - tests/**
      - '*.json'
      - action.yaml
      - .github/workflows/ts.yaml
  push:
    branches:
      - main
    paths:
      - src/**
      - tests/**
      - '*.json'
      - action.yaml
      - .github/workflows/ts.yaml

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
        with:
          node-version: 16
          cache: yarn
      - run: yarn
      - run: yarn test
      - run: yarn build
      - run: yarn package

      - uses: int128/deployment-action@26be42e8034c8d914387a117e66405129dc2f38e # v1.22.0
        id: app1
        with:
          environment-suffix: /app1
      - uses: int128/deployment-action@26be42e8034c8d914387a117e66405129dc2f38e # v1.22.0
        id: app2
        with:
          environment-suffix: /app2
      - uses: int128/deployment-action@26be42e8034c8d914387a117e66405129dc2f38e # v1.22.0
        id: app3
        with:
          environment-suffix: /app3
      - name: e2e-test
        uses: ./

      - uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # v6.4.1
        env:
          deployment_id: ${{ steps.app1.outputs.id }}
        with:
          script: |
            await github.rest.repos.createDeploymentStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              deployment_id: process.env.deployment_id,
              state: 'success',
              log_url: `https://argocd.example.com/pr-${context.issue.number}--app1`,
            })
      - name: e2e-test
        uses: ./

      - uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # v6.4.1
        env:
          deployment_id: ${{ steps.app2.outputs.id }}
        with:
          script: |
            await github.rest.repos.createDeploymentStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              deployment_id: process.env.deployment_id,
              state: 'success',
              log_url: `https://argocd.example.com/pr-${context.issue.number}--app2`,
            })
      - name: e2e-test
        uses: ./

      - uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # v6.4.1
        env:
          deployment_id: ${{ steps.app3.outputs.id }}
        with:
          script: |
            await github.rest.repos.createDeploymentStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              deployment_id: process.env.deployment_id,
              state: 'success',
              log_url: `https://argocd.example.com/pr-${context.issue.number}--app3`,
            })
      - name: e2e-test
        uses: ./

  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
        with:
          node-version: 16
          cache: yarn
      - run: yarn
      - run: yarn lint --fix
      - run: yarn format
      - uses: int128/update-generated-files-action@c340c8e219a7159fc46417d34f4cb3ff6eac47ac # v2.40.0
