name: ts

on:
  pull_request:
    paths:
      - src/**
      - tests/**
      - '*.json'
      - action.yaml
      - .github/workflows/ts.yaml
  push:
    branches:
      - main
    paths:
      - src/**
      - tests/**
      - '*.json'
      - action.yaml
      - .github/workflows/ts.yaml

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
        with:
          node-version: 16
          cache: yarn
      - run: yarn
      - run: yarn test

  create-deployments:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      app1: ${{ steps.app1.outputs.id }}
      app2: ${{ steps.app2.outputs.id }}
      app3: ${{ steps.app3.outputs.id }}
    steps:
      - uses: int128/deployment-action@0fc1a17bb2a6508c8380ddc1d2795e35dacd129c # v1.23.0
        id: app1
        with:
          environment-suffix: /app1
      - uses: int128/deployment-action@0fc1a17bb2a6508c8380ddc1d2795e35dacd129c # v1.23.0
        id: app2
        with:
          environment-suffix: /app2
      - uses: int128/deployment-action@0fc1a17bb2a6508c8380ddc1d2795e35dacd129c # v1.23.0
        id: app3
        with:
          environment-suffix: /app3

  e2e-test:
    needs: create-deployments
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
        with:
          node-version: 16
          cache: yarn
      - run: yarn
      - run: yarn build
      - run: yarn package
      - name: Run int128/aggregate-deployments-action
        uses: ./

      - uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # v6.4.1
        env:
          deployment_id: ${{ needs.create-deployments.outputs.app1 }}
        with:
          script: |
            await github.rest.repos.createDeploymentStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              deployment_id: process.env.deployment_id,
              state: 'success',
              log_url: `https://argocd.example.com/pr-${context.issue.number}--app1`,
            })
      - name: Run int128/aggregate-deployments-action
        uses: ./

      - uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # v6.4.1
        env:
          deployment_id: ${{ needs.create-deployments.outputs.app2 }}
        with:
          script: |
            await github.rest.repos.createDeploymentStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              deployment_id: process.env.deployment_id,
              state: 'success',
              log_url: `https://argocd.example.com/pr-${context.issue.number}--app2`,
            })
      - name: Run int128/aggregate-deployments-action
        uses: ./

      - uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # v6.4.1
        env:
          deployment_id: ${{ needs.create-deployments.outputs.app3 }}
        with:
          script: |
            await github.rest.repos.createDeploymentStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              deployment_id: process.env.deployment_id,
              state: 'success',
              log_url: `https://argocd.example.com/pr-${context.issue.number}--app3`,
            })
      - name: Run int128/aggregate-deployments-action
        uses: ./

  e2e-test-wait:
    needs: create-deployments
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
        with:
          node-version: 16
          cache: yarn
      - run: yarn
      - run: yarn build
      - run: yarn package
      - name: Run int128/aggregate-deployments-action
        uses: ./
        with:
          wait-until: completed
          wait-initial-delay-seconds: 0
          wait-period-seconds: 3

  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
        with:
          node-version: 16
          cache: yarn
      - run: yarn
      - run: yarn lint --fix
      - run: yarn format
      - uses: int128/update-generated-files-action@b928348b371fb2d3a2ee8e5804358e6e94780ebd # v2.41.0
