name: ts

on:
  pull_request:
    paths:
      - src/**
      - tests/**
      - '*.json'
      - action.yaml
      - .github/workflows/ts.yaml
  push:
    branches:
      - main
    paths:
      - src/**
      - tests/**
      - '*.json'
      - action.yaml
      - .github/workflows/ts.yaml

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4.0.0
        with:
          node-version: 20
          cache: yarn
      - run: yarn
      - run: yarn test

  create-deployments:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      app1: ${{ steps.app1.outputs.id }}
      app2: ${{ steps.app2.outputs.id }}
      app3: ${{ steps.app3.outputs.id }}
    steps:
      - uses: int128/deployment-action@5be0a91e042fcdf3e6aa0cb0ba735ef6fae15eb5 # v1.27.0
        id: app1
        with:
          environment-suffix: /app1
      - uses: int128/deployment-action@5be0a91e042fcdf3e6aa0cb0ba735ef6fae15eb5 # v1.27.0
        id: app2
        with:
          environment-suffix: /app2
      - uses: int128/deployment-action@5be0a91e042fcdf3e6aa0cb0ba735ef6fae15eb5 # v1.27.0
        id: app3
        with:
          environment-suffix: /app3

  e2e-test:
    needs: create-deployments
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4.0.0
        with:
          node-version: 20
          cache: yarn
      - run: yarn
      - run: yarn build
      - run: yarn package
      - name: Run int128/aggregate-deployments-action
        uses: ./

      - uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        env:
          deployment_id: ${{ needs.create-deployments.outputs.app1 }}
        with:
          script: |
            await github.rest.repos.createDeploymentStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              deployment_id: process.env.deployment_id,
              state: 'success',
              log_url: `https://argocd.example.com/pr-${context.issue.number}--app1`,
            })
      - name: Run int128/aggregate-deployments-action
        uses: ./

      - uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        env:
          deployment_id: ${{ needs.create-deployments.outputs.app2 }}
        with:
          script: |
            await github.rest.repos.createDeploymentStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              deployment_id: process.env.deployment_id,
              state: 'success',
              log_url: `https://argocd.example.com/pr-${context.issue.number}--app2`,
            })
      - name: Run int128/aggregate-deployments-action
        uses: ./

      - uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        env:
          deployment_id: ${{ needs.create-deployments.outputs.app3 }}
        with:
          script: |
            await github.rest.repos.createDeploymentStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              deployment_id: process.env.deployment_id,
              state: 'success',
              log_url: `https://argocd.example.com/pr-${context.issue.number}--app3`,
            })
      - name: Run int128/aggregate-deployments-action
        uses: ./

  e2e-test-wait:
    needs: create-deployments
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4.0.0
        with:
          node-version: 20
          cache: yarn
      - run: yarn
      - run: yarn build
      - run: yarn package
      - name: Run int128/aggregate-deployments-action
        uses: ./
        with:
          wait-until: completed
          wait-initial-delay-seconds: 0
          wait-period-seconds: 3

  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4.0.0
        with:
          node-version: 20
          cache: yarn
      - run: yarn
      - run: yarn lint --fix
      - run: yarn format
      - uses: int128/update-generated-files-action@75cb66681c401e4baf3ff82c4137f3dc1e53cc56 # v2.46.0
